### ISSUE TITLE
Missing --allow-live flag

### ISSUE THREAD

**Issue by ythecombinator** [pgrimaud/action-shopify#6]
_theme-kit_ recently made this `--allow-live` flag [required](https://github.com/Shopify/themekit/pull/739 ) for pushing changes to live themes.

Then production builds using this action now fail with the following error:

`[development] This is the live theme on <store>. If you wish to make changes to it, then you will have to pass the --allow-live flag`

A solution for this would be either:

- to lock the used theme-kit version
- or to add this flag [here](https://github.com/pgrimaud/action-shopify/blob/master/entrypoint.sh#L3)

What do you think @pgrimaud?

(Btw, thanks for this amazing GH action 💯 )

**Comment by pgrimaud** [comment]
Hi @ythecombinator 

Nice catch, I added the `--allow-live` flag 😄

**Comment by ythecombinator** [comment]
Perfect! Thanks 👍
