### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by ythecombinator** [pgrimaud/action-shopify#8]
Hello, 

I have a couple of workflows running using your action but something really weird started to happen in the last ~18hrs: all action runs fail with the following error: `Docker build failed with exit code 1`. 

Specifically, it fails when importing this python module:

<img width="1079" alt="Screen Shot 2020-12-03 at 13 28 40" src="https://user-images.githubusercontent.com/2644563/101018257-825f7980-356b-11eb-8b71-88b22591540c.png">

Any ideas?

**Comment by pgrimaud** [comment]
Hello, 

Could you try to upgrade to the last version? (2.1.2)

**Comment by ythecombinator** [comment]
Oh, I checked open issues like a few hours ago; hadn't realized there was a PR for this 😅 

That did the trick! Thanks 😃
